In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/reeno005/house-data/Scraped_Data.csv

In [2]:
OG_Data = pd.read_csv("/kaggle/input/datasets/reeno005/house-data/Scraped_Data.csv")
OG_Data.sample(10)

,exactPrice,sqftPrice,securityDeposit,propertyType,postedOn,noOfLifts,maintenanceChargesFrequency,maintenanceCharges,locality,furnishing,...,Cafeteria_Or_Food_Court,CCTV_Camera,Barbeque_Pit,Bar_Or_Lounge,Banquet_Hall,Bank__And__ATM,Arts__And__Craft_Studio,Air_Conditioned,Activity_Deck4,AEROBICS_ROOM
10857,25000,20,20000,Multistorey Apartment,"Jun 30, '23",9.0,Monthly,2000,Raja Park,Semi-Furnished,...,9,9,9,9,9,9,9,9,9,9
7159,6500,11,9,Residential House,"Jun 30, '23",9.0,9,9,Banashankari stage 6,Semi-Furnished,...,9,9,9,9,9,9,9,9,9,9
20261,6500000,5909,9,Multistorey Apartment,"Feb 19, '23",9.0,9,9,C-Scheme,Unfurnished,...,9,9,9,9,9,9,9,9,9,9
5995,13000,16,9,Builder Floor Apartment,"Jun 29, '23",9.0,9,9,Madipakkam,Semi-Furnished,...,9,9,9,9,9,9,9,9,9,9
26081,19000000,2381,9,Residential House,"Jun 16, '23",9.0,9,9,Doiwala,Semi-Furnished,...,9,9,9,9,9,9,9,9,9,9
1916,15000,14,45000,Multistorey Apartment,"Jun 16, '23",NaN,Monthly,6000,Colva,Unfurnished,...,9,9,9,9,9,9,9,9,9,9
26715,4200000,2897,9,Residential House,"May 14, '23",9.0,9,9,Kursi Road,Unfurnished,...,0,0,0,0,0,0,0,0,0,0
500,4000,4,9,Residential House,"Apr 23, '23",9.0,9,9,Kurthaul,Semi-Furnished,...,9,9,9,9,9,9,9,9,9,9
9348,8500,14,9,Multistorey Apartment,"May 24, '23",9.0,9,9,Ayodhya Bypass,Unfurnished,...,0,0,0,0,0,0,0,0,0,0
22403,5500000,3793,9,Builder Floor Apartment,"Apr 04, '23",9.0,9,9,Nirman Nagar,Semi-Furnished,...,9,9,9,9,9,9,9,9,9,9

In [3]:
OG_Data.describe()

,exactPrice,sqftPrice,securityDeposit,noOfLifts,maintenanceCharges,firstMonthCharges,totalFlrNum,carpetArea,bedrooms,bathrooms,...,Cafeteria_Or_Food_Court,CCTV_Camera,Barbeque_Pit,Bar_Or_Lounge,Banquet_Hall,Bank__And__ATM,Arts__And__Craft_Studio,Air_Conditioned,Activity_Deck4,AEROBICS_ROOM
count,2.790000e+04,2.790000e+04,2.790000e+04,27445.000000,2.790000e+04,2.790000e+04,27900.000000,27900.000000,27900.000000,27900.000000,...,27900.000000,27900.000000,27900.00000,27900.000000,27900.000000,27900.000000,27900.000000,27900.000000,27900.000000,27900.000000
mean,5.427532e+06,4.293275e+04,2.407937e+04,7.870978,2.902351e+05,3.327781e+05,5.665520,609.963584,2.673047,2.483082,...,7.152724,7.155484,7.12319,7.133513,7.175627,7.134624,7.121900,7.141792,7.127204,7.147455
std,2.699586e+07,2.264502e+06,1.074923e+05,2.602134,4.835278e+07,4.835763e+07,7.012247,837.434426,1.418080,1.490751,...,3.594546,3.589433,3.64868,3.629878,3.551828,3.627847,3.651021,3.614706,3.641383,3.604280
min,9.000000e+00,0.000000e+00,1.000000e+00,1.000000,0.000000e+00,9.000000e+00,1.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.300000e+04,1.100000e+01,9.000000e+00,9.000000,9.000000e+00,9.000000e+00,2.000000,9.000000,2.000000,2.000000,...,9.000000,9.000000,9.00000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000
50%,3.000000e+04,2.100000e+01,9.000000e+00,9.000000,9.000000e+00,9.000000e+00,4.000000,125.000000,2.000000,2.000000,...,9.000000,9.000000,9.00000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000
75%,5.269500e+06,3.864250e+03,1.400000e+04,9.000000,9.000000e+00,3.000000e+04,7.000000,1050.000000,3.000000,3.000000,...,9.000000,9.000000,9.00000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000
max,3.250000e+09,2.000000e+08,5.000000e+06,10.000000,8.076500e+09,8.076537e+09,200.000000,13000.000000,10.000000,10.000000,...,9.000000,9.000000,9.00000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000

**We need to drop some of the columns that are not in use**

**First we need to make the copy of the data so the Real data doesn't get hamper!**

In [4]:
data = OG_Data.copy()
data.sample(1)

,exactPrice,sqftPrice,securityDeposit,propertyType,postedOn,noOfLifts,maintenanceChargesFrequency,maintenanceCharges,locality,furnishing,...,Cafeteria_Or_Food_Court,CCTV_Camera,Barbeque_Pit,Bar_Or_Lounge,Banquet_Hall,Bank__And__ATM,Arts__And__Craft_Studio,Air_Conditioned,Activity_Deck4,AEROBICS_ROOM
25749,6500000,5000,9,Residential House,"Mar 16, '23",9.0,9,9,IIM Road,Semi-Furnished,...,9,9,9,9,9,9,9,9,9,9

In [5]:
data.rename(columns = {'noOfLifts':'no_of_lifts'}, inplace=True)
data

,exactPrice,sqftPrice,securityDeposit,propertyType,postedOn,no_of_lifts,maintenanceChargesFrequency,maintenanceCharges,locality,furnishing,...,Cafeteria_Or_Food_Court,CCTV_Camera,Barbeque_Pit,Bar_Or_Lounge,Banquet_Hall,Bank__And__ATM,Arts__And__Craft_Studio,Air_Conditioned,Activity_Deck4,AEROBICS_ROOM
0,240000,171,9,Multistorey Apartment,"Jun 20, '23",9.0,9,9,Danapur,Semi-Furnished,...,1,0,0,1,1,0,0,0,0,0
1,12000,12,12000,Multistorey Apartment,"Jun 19, '23",1.0,Monthly,1500,9,Semi-Furnished,...,9,9,9,9,9,9,9,9,9,9
2,17000,7,9,Residential House,"Jun 21, '23",9.0,9,9,Phase 1 Ashiana Nagar,Semi-Furnished,...,9,9,9,9,9,9,9,9,9,9
3,5000,9,9,Residential House,"Jun 23, '23",9.0,9,9,Kumhrar,Furnished,...,9,9,9,9,9,9,9,9,9,9
4,12000,9,24000,Multistorey Apartment,"Jun 24, '23",1.0,Monthly,500,Kumhrar,Unfurnished,...,9,9,9,9,9,9,9,9,9,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27895,20227500,7500,9,Multistorey Apartment,"Jul 01, '23",2.0,Monthly,9,Dalanwala,Semi-Furnished,...,0,0,0,0,0,0,0,0,0,0
27896,6933500,4900,9,Multistorey Apartment,"Jun 30, '23",9.0,9,9,Canal Road,Semi-Furnished,...,0,0,0,0,0,0,0,0,0,0
27897,9000000,8182,9,Villa,"Jul 02, '23",9.0,9,9,Aman Vihar,Unfurnished,...,9,9,9,9,9,9,9,9,9,9
27898,7645000,5500,9,Multistorey Apartment,"Jul 01, '23",9.0,9,9,Sahastradhara Road,Unfurnished,...,0,0,0,1,0,0,0,0,0,0
27899,11525400,5700,9,Multistorey Apartment,"Jun 30, '23",2.0,Monthly,9,General Mahadev Singh Road,Semi-Furnished,...,0,0,0,0,0,0,0,0,0,0

In [6]:
data['furnishing'].unique()

array(['Semi-Furnished', 'Furnished', 'Unfurnished', '9'], dtype=object)

In [7]:
data['locality'].unique()

array(['Danapur', '9', 'Phase 1 Ashiana Nagar', ..., 'Curzon Road',
       'Malhour', 'Prakash Lok Colony'], dtype=object)

In [8]:
data['maintenanceChargesFrequency'].unique()

array(['9', 'Monthly', 'Quarterly', 'Yearly', 'One-Time',
       'Per sq. Unit Monthly'], dtype=object)

In [9]:
data['maintenanceCharges'].unique()

array([         9,       1500,        500,       2000,       1000,
              200,        100,      17000,      27000,       5000,
             3500,       1200,       4000,       2500,        300,
             1400,       3000,       1700,       2400,       1600,
             1300,       1800,        350,        800,        150,
             1100,      10000,          1,       1735,       1840,
            28000,      25000,      12000,        750,       2450,
              900,        250,        700,      10004,       2100,
              166,         20,       1250,       2200,        120,
             3300,      15000,       6000,       3250,        400,
             2300,       7000,         50,      43000,      19000,
               30,         41,       2800,       1111,        600,
              416,         80,      20000,          0,       5100,
             1666,        650,       3400,         83,       4800,
              333,       8000,       2310,       3200,          5,
             1875,       1166,         62,          3,        850,
             6350,       4500,       2600,       1985,       4600,
              780,       2222,       1921,       4513,       1220,
               33,       1350,       5500,       3294,        555,
             1640,          2,        175,       1770,        360,
             3600,       1333,      10001,       2150,       6069,
             5400,       5140,       7988,       9300,       4666,
             4750,       1050,      12999,       3800,       2350,
             1125,        550,       4900,       7500,       4460,
             1670,       9000,       1667,        999,       2900,
             5050,       1130,       1080,       1416,       5808,
            16000,      11500,      25500,       2155,      30000,
            11000,      14000,        125,       2950,        233,
             3700,        833,       6750,       2700,       5700,
             4210,      11281,       6200,       2250,        815,
             6500,       1450,       4700,       5300,       1560,
              553,       1815,       1550,       4400,      10500,
            35000,       2375,       8500,          4,      31000,
             8250,       3560,       6700,      70000,      13000,
             7250,       7200,        450,       7300,      17500,
            19054,       1483,      50000,      11800,       3100,
            18000,      80000,       5800,       7600,      12500,
              165,      10800,       4300,      10300,       8333,
             5888,      30006,      10230,       3980,       6100,
             1900,       5222,      29000,       9400,       5200,
             3550,       5250,       7800,         10,        370,
             1272,       3950,       5430,       1650,       4850,
             2660,       3249,        824,       1316,        820,
            32000,       2980,       3333,       1160,       3030,
              889,       1016,        950, 8076500000,       4060,
              295,       4330,       1298,       1610,       1055,
             4200,       2612,       2083,       2365,       2166,
              640,     100000,       1170,       1810,       3666,
               66,        611,       2175,       1850,      13500,
             4446,       3150,       5240,       1730,       1781,
             2050,       2106,       4350,   11000000,       2020,
             2080,       3070])